### ISSUE TITLE
module Zone 1 settings will not be saved

### ISSUE THREAD

**Issue by mrmuffin1308** [widapro/wled-pixel-v2#1]
First of all thank you for your great work.

I have a problem that when I change the Display setting of First and Last Module [Zone 1} it will not be saved.

**Comment by widapro** [comment]
Thank you for your feedback. Please try this new release: https://github.com/widapro/wled-pixel-v2/releases/tag/v2.1

**Comment by mrmuffin1308** [comment]
thanks , the new release solved the problem.
