### ISSUE TITLE
open weather map

### ISSUE THREAD

**Issue by Grey-Lancaster** [widapro/wled-pixel-v2#5]
I tried it and got banned :)

Your API key is blocked.

Dear Customer,
Your OpenWeatherMap API key 2b07989e82de77d0ef5b9xxxxxxxx5 is temporary blocked due to the continual sufficient exceeding of the calls per minute limit by performing 633 requests within a minute but the limit for the Free account is 60 rpm.

To unblock your API key and restore the normal operation with the weather API we ask you to suppress the loading from your API keys or upgrade your subscription. Contact us [info@openweathermap.org](mailto:info@openweathermap.org?subject=My%20API%20key%20is%20blocked) for any help with choosing the proper type of the subscription.

**Comment by Grey-Lancaster** [comment]
perhaps the format of the city was off?

**Comment by widapro** [comment]
I thought that finding the city ID is difficult and easier to write the name of the city. But I forgot to add on the page that you need to enter the name of the city.

Pay attention that the free OWM API allows you to make requests no more than once every 60 seconds, otherwise you will be banned.

**Comment by Grey-Lancaster** [comment]
Landum, US worked right away
for some reason if it is off it seems to send a lot of calls
Thanks,
Grey
